name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        
    
      
    - name: make
      run: |

            # Commands:

            sudo apt-get install ant #//If you install manually - set envirnoment value to Ant

            sudo apt-get install make

            sudo apt-get install g++

            sudo apt-get install git-core
            sudo chmod 777 gradlew
            gradle init
            ./gradlew clean assembleDebug --no-daemon --stacktrace
            ls -l
            
            
    - name: Upload result for job
      uses: actions/upload-artifact@v1
      with:
          name: Build
          path: app/build
